# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
flutter_application_path = '../flutterproject'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'MyiOSTest' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!

  # Pods for MyiOSTest
#pod 'AFNetworking', '4.0.1'
install_all_flutter_pods(flutter_application_path)
end
